# build.yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.g.dart'
      freezed|freezed:
        options:
          build_extensions:
            '^lib/src/{{}}.dart': 'lib/src/generated/{{}}.freezed.dart'